export const DASHBOARD_CONFIG = {
  // Categories shown in the material matrix
  MATRIX_CATEGORIES: ['Wood', 'Metal', 'Stone', 'Cloth', 'Farming', 'Fishing', 'Leather'],

  // Category mappings: which tags belong to which high-level category
  TAG_CATEGORIES: {
    Wood: ['Wood Log', 'Plank', 'Bark', 'Timber', 'Trunk', 'Stripped Wood'],
    Metal: ['Ingot', 'Ore', 'Ore Concentrate', 'Ore Chunk', 'Nail', 'Molten Ingot'],
    Stone: [
      'Pebbles',
      'Brick',
      'Clay',
      "Potter's Mix",
      'Chunk',
      'Geode',
      'Sand',
      'Glass',
      'Gypsite',
    ],
    Cloth: ['Plant Fiber', 'Thread', 'Cloth', 'Cloth Strip', 'Filament', 'Rope'],
    Farming: [
      'Fertilizer',
      'Grain',
      'Grain Seeds',
      'Vegetable',
      'Vegetable Seeds',
      'Filament Seeds',
      'Berry',
      'Flower',
      'Mushroom',
      'Vegetable Plant',
      'Filament Plant',
      'Roots',
    ],
    Fishing: [
      'Bait',
      'Lake Fish',
      'Lake Fish Filet',
      'Ocean Fish',
      'Oceanfish Filet',
      'Chum',
      'Fish Oil',
      'Crushed Shells',
      'Baitfish',
    ],
    Leather: ['Leather', 'Raw Pelt', 'Cleaned Pelt', 'Tanned Pelt', 'Tannin', 'Raw Meat'],
    Food: ['Basic Food', 'Meal', 'Dough'],
    Scholar: ['Parchment', 'Journal', 'Ancient Hieroglyphs', 'Ink', 'Pigment'],
    Packages: ['Package', 'Sheeting'],
    Gems: ['Gem', 'Gem Fragment'],
    Tools: [
      'Forester Tool',
      'Miner Tool',
      'Farmer Tool',
      'Tailor Tool',
      'Mason Tool',
      'Blacksmith Tool',
      'Hunter Tool',
      'Forager Tool',
      'Carpenter Tool',
      'Scholar Tool',
    ],
  },

  // Tags that count as "raw materials" for tier aggregation
  RAW_MATERIAL_TAGS: new Set([
    'Wood Log',
    'Plank',
    'Bark',
    'Timber',
    'Trunk',
    'Ingot',
    'Ore Concentrate',
    'Ore Chunk',
    'Nail',
    'Pebbles',
    'Brick',
    'Clay',
    "Potter's Mix",
    'Chunk',
    'Sand',
    'Glass',
    'Plant Fiber',
    'Thread',
    'Cloth',
    'Filament',
    'Rope',
    'Fertilizer',
    'Grain',
    'Vegetable',
    'Bait',
    'Lake Fish',
    'Lake Fish Filet',
    'Ocean Fish',
    'Oceanfish Filet',
    'Chum',
    'Leather',
    'Tanned Pelt',
    'Tannin',
    'Raw Meat',
  ]),
  SUPPLY: new Set(['Frame', 'Timber', 'Tarp', 'Brick Slab', 'Sheeting']),

  // Supply cargo types for the production potential panel.
  // Tags match recipe tags exactly from recipes.json.
  // Discovered via diagnostic dump of actual recipe data.
  SUPPLY_TYPES: [
    { label: 'Timber', tag: 'Timber' },
    { label: 'Frames', tag: 'Frame' },
    { label: 'Tarp', tag: 'Tarp' },
    { label: 'Slab', tag: 'Brick Slab' },
    { label: 'Sheeting', tag: 'Sheeting' },
  ] as const,
  // Build reverse lookup: tag -> category (computed at load time)
  TAG_TO_CATEGORY: {} as Record<string, string>,
  // Inventory category display order
  CATEGORY_ORDER: [
    'Wood',
    'Metal',
    'Stone',
    'Cloth',
    'Farming',
    'Fishing',
    'Leather',
    'Packages',
    'Gems',
    'Tools',
    'Other',
  ],
  // Categories excluded from inventory grid (shown in quick stats instead)
  INVENTORY_GRID_EXCLUDE: ['Food', 'Scholar'],
  // Actual food to be shown in the food tab, incomplete and not yet used
  FRIDGE: ['Fine Deluxe Ocean Fish Sticks', 'Succulent Ocean Fish Sticks'],
  // rules for sorting food
  FOOD_RULE: [
    { words: ['fish'], prio: 0 },
    { words: ['meat'], prio: 1 },
    { words: ['mushroom', 'berry'], prio: 2 },
  ],
  // Amount of entries shown in the food dashboard
  FOOD_ENTRIES: 15,
  // Tier specifier
  SPECIFIER: [
    'Rough',
    'Basic',
    'Simple',
    'Sturdy',
    'Fine',
    'Exquisite',
    'Peerless',
    'Ornate',
    'Pristine',
    'Flawless',
    'Magnificent',
  ],
  BG_CONST: 'background: rgba(88, 166, 255, 0.2);',
  // Array containing the tailoring item names to be shown in the tailoring sub view
  TAILOR_TAGS: [
    'Cloth',
    'Cloth Strip',
    'Filament',
    'Plant Fiber',
    'Rope',
    'Refined Cloth',
    'Roots',
  ],
  TAILOR_ITEMS_ADDITIONAL: ["Clothmaker's Mordant"],
  TAILOR_PACKAGES: [],
  FARMING_TAGS: [
    'Filament Seeds',
    'Grain Seeds',
    'Vegetable Seeds',
    'Fertilizer',
    'Berry',
    'Mushroom',
    'Flower',
    'Grain',
    'Vegetable',
    'Filament',
  ],
  FARMING_ITEMS_ADDITIONAL: ['Water Bucket'],
  FARMING_PACKAGES: [],
  WOODWORKING_TAGS: [
    'Trunk',
    'Wood Log',
    'Stripped Wood',
    'Plank',
    'Bark',
    'Timber',
    "Potter's Mix",
    'Pebbles',
    'Clay',
    'Sapling',
    'Nail',
  ],
  WOODWORKING_ITEMS_ADDITIONAL: ['Empty Bucket', 'Water Bucket'],
  WOODWORKING_PACKAGES: ['Wood Log Package', 'Plank Package', 'Bark Package'],
  LEATHERWORKING_TAGS: ['Cleaned Pelt', 'Tanned Pelt', 'Leather', 'Raw Meat', 'Tannin', 'Pelt'],
  LEATHERWORKING_ITEMS_ADDITIONAL: ['Water Bucket', 'Hideworking Salt'],
  LEATHERWORKING_PACKAGES: [],
  MASONRY_TAGS: [
    'Stone Chunk',
    'Pebbles',
    'Clay',
    "Potter's Mix",
    'Unfired Brick',
    'Brick',
    'Stone Slab',
  ],
  MASONRY_ITEMS_ADDITIONAL: ['Brickworking Ash', 'Refined Brick'],
  MASONRY_PACKAGES: [],
  SMITHING_TAGS: [
    'Wood Logs',
    'Ore',
    'Ore Concentrate',
    'Ore Chunk',
    'Ingot',
    'Molten Ingot',
    'Nail',
    'Leather',
    'Plank',
    'Cloth',
    'Rope',
  ],
  SMITHING_ITEMS_ADDITIONAL: ['Metalsmelting Flux'],
  SMITHING_PACKAGES: [],
  FISHING_TAGS: [
    'Bait',
    'Baitfish',
    'Raw Meat',
    'Chum',
    'Crushed Shells',
    'Fish Oil',
    'Lake Fish',
    'Lake Fish Filet',
    'Ocean Fish',
    'Ocean Fish Filet',
  ],
  FISHING_ITEMS_ADDITIONAL: [],
  FISHING_PACKAGES: [],
  SCHOLAR_TAGS: ['Ancient Hieroglyphs', 'Ink', 'Journal', 'Parchment', 'Pigment'],
  SCHOLAR_ITEMS_ADDITIONAL: ['Water Bucket', 'Sugar'],
  SCHOLAR_PACKAGES: ['Bark Package'],
  COOKING_TAGS: ['Grain', 'Vegetable', 'Dough', 'Food', 'Ocean Fish Filet', 'Lake Fish Filet'],
  COOKING_ITEMS_ADDITIONAL: ['Sugar', 'Salt'],
  COOKING_PACKAGES: [],
};
// Initialize reverse lookup
for (const [category, tags] of Object.entries(DASHBOARD_CONFIG.TAG_CATEGORIES)) {
  for (const tag of tags) {
    DASHBOARD_CONFIG.TAG_TO_CATEGORY[tag] = category;
  }
}
